Add Basic UI
Ogaga01/school_library_OOP pull request #4
Opened 2022-07-21 17:07 UTC by Ogaga01

## Hello Reviewer 👋 

In this project milestone, I implemented the following requirements:

- Watch the video with the UI example again (you have seen it while reading the Sneak Peek).
    - [![UI example](https://img.youtube.com/vi/vkkgrhD6aXQ/0.jpg)](https://www.youtube.com/watch?v=vkkgrhD6aXQ)
- Your console app should behave in the same way is in the example.
- Create a `app.rb` file that will serve as your console app entry-point. It should have methods that do the following:
  - List all books.
  - List all people.
  - Create a person (teacher or student, not a plain `Person`).
  - Create a book.
  - Create a rental.
  - List all rentals for a given person id.
- In your `main.rb` define the entry point, this will be a method called `main` that is invoked at the end of your file. This method should do the following:
  - Present the user with a list of options to perform.
  - Lets users choose an option.
  - If needed, ask for parameters for the option.
  - Have a way to quit the app.

2022-07-21 18:36 UTC, KDlamini requested changes
### Hi @Ogaga01 🙋‍♀️,  

Great work so far! 💯 
There are some issues that you still need to work on to improve your project according to the requirements. You are almost there! 💪🏾 

## Highlights 🌞 
✔️  Good PR title
✔️  Good PR description
✔️  Correct use of Gitflow 
✔️  No linter errors

## Required Changes ♻️
 
 
**Kindly look through the comments below 👇 for required changes**

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

N/A

Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me @KDlamini  in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-21 18:36 UTC, KDlamini commented on app.rb
> +  end
Creating students currently doesn't work, it throws an error after choosing permission. Kindly look into your `create_student` method and make sure that it can create a student successfully.

![image](https://user-images.githubusercontent.com/38088818/180281253-cd1898e3-d9ff-4df9-bfc8-0d1cd6ac3e81.png)

- Pay close attention to the error message to get a clue about where the problem is. For example, in the last line of the error message, you have `person.rb:8:in 'initialize': wrong number of arguments (given 3, expected 1) (ArgumentError)`.  Therefore, the issue is in `person.rb` on `line 8`, and since this is an `(ArgumentError)` that tells you that the issue is with your parameters.

2022-07-21 18:36 UTC, KDlamini commented on app.rb
> +  end
Same here, creating teachers currently doesn't work, it throws an error after specialization. Kindly look into your `create_teacher` method and make sure that it can create a teacher successfully.

![image](https://user-images.githubusercontent.com/38088818/180281623-f80837c9-31f5-4be5-a815-b45758373524.png)

- Same here, to get an idea of the issue pay attention to the last line of the error message `app.rb:80:in 'create_teacher': undefined local variable or method 'name' `.  That should tell you that in `app.rb` `line 80` you have you used an undefined variable `name` within the `create_teacher` method.
-  This is one way you can debug and understand your errors in Ruby.

2022-07-21 18:36 UTC, KDlamini commented on app.rb
> +  end
After the above-mentioned issues are resolved kindly verify on the console to make sure that:

- You can successfully list all created persons
- You can create a rental with a permitted person
- You can list all rentals from a particular person using id

Well done on making the `create_book` and `list_all_books` methods work!!! 👏🏾

2022-07-22 09:20 UTC, Munsa1 approved these changes
Hi @Ogaga01, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
:heavy_check_mark: Descriptive Readme
:heavy_check_mark: Passing Linters
:heavy_check_mark: Correct Gitflow

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-22 12:53 UTC, merged